### ISSUE TITLE
Include a Window menu on Mac OS X

### ISSUE THREAD

**Issue by pcwalton** [andlabs/libui#102]
The Apple Human Interface Guidelines require that a Window menu be present: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW1

This should contain at least Minimize and Zoom menu items, as well as a list of all open windows. Happily, `setWindowsMenu:` will automatically maintain that list.

My instinct would be to just automatically include this menu on Mac OS X and to omit it on other platforms. I don't see a pressing need to get programmatic access to it at least for now, as apps rarely mess with it.

**Comment by andlabs** [comment]
Yeah, the default OS X menus are something I'm thinking about; see that other issue about accelerators.

Part of the thing to take into consideration with adding a Window menu is document based applications; I want to provide a facility for this as well. I'm not sure how they would work on Windows or Linux; for Windows MDI is deprecated and might come off as unnatural? But that's a long way away.

Adding it automatically is definitely doable, though isn't a good long-term solution, since people will expect it to the left of a Help menu and localization will make that a bit painful. I'll look into doing it after finalizing the cmake stuff, though (that will be marked by an alpha3.1).

**Comment by andlabs** [comment]
Replaced with #321.
