### ISSUE TITLE
Implement a way to set window position

### ISSUE THREAD

**Issue by parro-it** [andlabs/libui#130]

**Comment by andlabs** [comment]
The only thing is: should the position be set relative to the top left corner of the content area or to the window decoration? The latter is easier but since sizes use the content area (or are supposed to) the former would be more logical...

**Comment by parro-it** [comment]
I will expect that setting the position to 0,0 the window is positioned on the top left corner, with decorations fully visible. 
I didn't noticed that the size of the window is actually related to the content area, it could also be useful to have a way to set it related to the whole window.
I don't think is a big concern if the two features uses different semantic (content for size and content+decorations for position)

**Comment by andlabs** [comment]
Sure, I guess it doesn't really cause a problem.

I chose to make sizes content-based because a) it's simpler on some platforms (like OS X) b) it means you can ask for a 640x480 window and actually get 640x480 pixels, rather than 640x480 minus the size of the decorations, which can vary from computer to computer.

**Comment by parro-it** [comment]
I consider content-based size a great feature! I just didn't expect it because many toolkit doesn't implement it...

**Comment by andlabs** [comment]
```
[15:24:43]  <mclasen>	windows don't even have a position on wayland
```

**Comment by andlabs** [comment]
Positions done.
