### ISSUE TITLE
Request: Change uiArea/uiAreaHandler callback API

### ISSUE THREAD

**Issue by wasamasa** [andlabs/libui#167]
I find it rather unelegant that every widget except uiArea has a function for registering a callback, yet uiArea goes for a struct containing five different callbacks.  My other problem with this is that it unnecessarily complicates things for FFI.  Please turn uiArea into a regular widget that allows registering callbacks as one needs to.

**Comment by parro-it** [comment]
@wasamasa `uiAreaHandler` is not exactly representing a group of unrelated callbacks, but rather an interface implementation that `uiArea` expect to receive to handle drawing.
Al other callbacks in `libui` instead are representing ui events handler.
I think that the current implementation make the difference clearer than what you are suggesting...

**Comment by wasamasa** [comment]
@parro-it I'm not sure I understand.  The `Draw` member is the only one in this struct concerned with drawing, the remaining ones represent UI events.  As for interfaces, fine, but isn't that an implementation detail as opposed to the API one writes bindings for?

**Comment by parro-it** [comment]
> The Draw member is the only one in this struct concerned with drawing, the remaining ones represent UI events

Yes, the other are events, but once you group them in an interface, it could represent a custom widget with it's own drawing, mouse & keyboard event handling. This is because I like the API as it is. But maybe I didn't correctly understand Pietro intentions...

He provided some details on the design here: https://github.com/charto/nbind/issues/20

**Comment by duckbrain** [comment]
So do you want something like [this](https://gist.github.com/duckbrain/fea63f8731bfef36440620448a2aa6b8)? The Area is good for creating custom controls. Those controls are likely to want to use the mouse and key events to handle user input as well as drawing.

**Comment by wasamasa** [comment]
OK, that explanation makes a bit more sense.  Still, I find it sort of iffy for things designed to be wrapped to be using structs as part of their API, especially when it's inconsistent with the rest of it.

**Comment by ghaberek** [comment]
With my [libui-euphoria](https://github.com/ghaberek/libui-euphoria/) wrapper I had to create a set of functions to build the `uiAreaHandler` interface manually because Euphoria does not (yet) support C structures. Basically, it allocates the structure into memory and then sets each call back with a separate function call. (The allocated structure is free automatically when it goes out of scope.)

https://github.com/ghaberek/libui-euphoria/blob/master/include/libui/ui.e#L1043

This same interface could probably be implemented in C to support what @wasamasa is looking for.

    uiAreaHandler *uiNewAreaHandler();
    void uiFreeAreaHandler( uiAreaHandler *ah );
    void uiAreaSetDrawHandler( uiAreaHandler *ah, void (*Draw)(uiAreaHandler *, uiArea *, uiAreaDrawParams *) );
    void uiAreaSetMouseEventHandler( uiAreaHandler *ah, void (*MouseEvent)(uiAreaHandler *, uiArea *, uiAreaMouseEvent *) );
    void uiAreaSetMouseCrossedHandler( uiAreaHandler *ah, void (*MouseCrossed)(uiAreaHandler *, uiArea *, int left) );
    void uiAreaSetDragBrokenHandler( uiAreaHandler *ah void (*DragBroken)(uiAreaHandler *, uiArea *) );
    void uiAreaSetKeyEventHandler( uiAreaHandler *ah, int (*KeyEvent)(uiAreaHandler *, uiArea *, uiAreaKeyEvent *) );

Ultimately, the internal code that calls these functions needs to account for the possibility that they may be `NULL`, which I'll admit is a flaw in my current implementation for Euphoria. I'm relying on the user of the API to set all five functions before calling any further `uiArea` functions.

**Comment by wasamasa** [comment]
Now that I think of it, this kind of design makes it harder to support passing a data argument like for all other callbacks.  Traditionally this is solved by adding a member of void pointer type, but that would be a step back compared to the rest as you now have to combine all your data into one variable for this to work.

**Comment by ghaberek** [comment]
> Now that I think of it, this kind of design makes it harder to support passing a data argument like for all other callbacks. Traditionally this is solved by adding a member of void pointer type, but that would be a step back compared to the rest as you now have to combine all your data into one variable for this to work.

@andlabs could add any number of new members to the `uiAreaHandler` structure and then you could retrieve them from your callback functions. This would work with the existing API since the callback functions already receive the `uiAreaHandler` pointer as their first parameter.

**Comment by andlabs** [comment]
Merged with #326.
