### ISSUE TITLE
Any c++ bindings?

### ISSUE THREAD

**Issue by eskin** [andlabs/libui#217]
subj.

**Comment by parro-it** [comment]
It's not specifically target at C++, but to develop bindings for node.js, I wrapped all the API with c++.
Yuo can see it here: https://github.com/parro-it/libui-node

**Comment by andlabs** [comment]
If people make any C++ bindings intended for standalone use I can add them to the README.

**Comment by parro-it** [comment]
There is https://github.com/billyquith/libui-cpp, but seems to be uncompleted...

**Comment by aoloe** [comment]
i've also started working on c++ bindings... but i stopped and i'm waiting to know in which direction libui is going.

my goal is to have bindings that are as close as possible to Qt:

- because Qt is mostly sane and
- to allow people to start a project with libui and easily move to Qt if they ever feel the need for something "bigger".

the code is here

https://github.com/aoloe/cpp-libui-qtlike

but, please, don't link to it yet in the README file.
(but if somebody feels like working on it, get in touch with me... or simply fork it and hack on it!)

**Comment by andlabs** [comment]
Putting both up anyway. Will close this topic now; if any new developments come up, let me know.
