### ISSUE TITLE
Support for file input?

### ISSUE THREAD

**Issue by Xeoncross** [andlabs/libui#248]
Looking over the control gallery example, the todo, and the project files I don't see any mention of a file input/selector. Since you even have a color picker I'm assuming that a file selector is a complex element and something has prevented it's addition so far.

**Comment by andlabs** [comment]
There is no dedicated file selector control; there is `uiOpenFile()` and `uiSaveFile()`, which open dialog boxes to select files. The controlgallery example uses that.

The reason the font and color buttons are buttons instead of direct dialogs themselves is because on OS X you use those dialogs modelessly — they operate like floating tool palettes, like the Layers panel in Photoshop, and your changes get applied to the currently selected item. On Windows and GTK+, font and color selection are modal: you stop what you are doing and select a font or color. Of course, GTK+ might make it possible to make modeless color selection, and since I have a custom font and color panel on Windows I could easily make them modeless too, but then I have to do the work to copy the OS X color/font model over... Until then, on OS X, the buttons have to be active in order for the color/font panel to work, and the color/font panels's notifications are forcibly redirected to the buttons responsible. (The color button is a subclass of NSColorWell, which is already provided by OS X; I'm not sure how those are supposed to be used. The font button is a NSButton subclass. It also just so happens that GTK+ also provides font and color buttons that do the work of opening the dialog for you.)

**Comment by Xeoncross** [comment]
Thank you for the explanation... and your work on this project. `uiOpenFile()` is what I was looking for.
