### ISSUE TITLE
intmax_t and uintmax_t problematic for some languages FFI

### ISSUE THREAD

**Issue by benpye** [andlabs/libui#25]
I am currently writing a library for C# wrapping libui for .NET Core. I have generally found the library structured very well for being wrapped for usage in another language. One issue I have come across is the usage of `intmax_t` and `uintmax_t`. C# has no equivalent for these types (and I suspect other languages also have this limitation), and as such I am currently assuming that they are 64 bit integers, but this could not be true. If the API could instead expose these as some fixed width integer then this would be much easier to deal with, especially when wanting to target any Windows, Linux or OS X system.

**Comment by andlabs** [comment]
Yes, I've been thinking about that as well, though more for "warning: you're converting a larger type to a smaller type" reasons. I wonder if I could just make them `int` and `unsigned int` instead (or get rid of `uintmax_t` entirely and just use `int`).

**Comment by Someguynamedpie** [comment]
Could use types like uint32_t or uint64_t

**Comment by pcwalton** [comment]
In Rust I'm just mapping these to `i64` and `u64`, as that is what the Rust `libc` crate defines `intmax_t` and `uintmax_t` as.

**Comment by andlabs** [comment]
I'm tempted to just use long, under the rationale that nothing should really exceed 2 billion objects anyway. I'm not sure if I'd be comfortable pinning to int64 if we ever move beyond 64-bit... I'm open to arguments for or against anything though :)

**Comment by zevv** [comment]
For the Combobox, Box and Tab indices an unsigned int should be just fine

The slider might benefit from using a floating point type for more flexibility, but I'm not sure of all the various OS backends support this.

**Comment by billyquith** [comment]
How does it deal with size_t?

Could you do something like this? http://stackoverflow.com/a/9203792/3233

**Comment by andlabs** [comment]
So what should it be, int or long?

**Comment by billyquith** [comment]
So the problem is that `int` and `long` are 32 and 64 bits for C#, regardless (word size is only relevant in the JIT compiler). So, how about:

Define in your LibUI C config header:

```c
#ifndef UI_SIZE_T
#define UI_SIZE_T size_t
#endif
typedef UI_SIZE_T ui_size_t;
```

Then in cmake config you allow a variable `BUILD_SIZE_T` which is defined if the user wants to compile LibUI with a different type for size_t. The default works for C, C++, etc. For C# you generate a project with:

```
cmake .. -G xxx  -D UI_SIZE_T=uint64_t
```

In cmake config:

```cmake
if(BUILD_SIZE_T)
    add_definitions("UI_SIZE_T=${BUILD_SIZE_T})
endif()
```

Then `ui_size_t` is always passed and returned as `uint64_t`. This may produce some type data loss warning when this is used but this should be safe as long as the client code is aware of whether LibUI is compiled as 32 or 64 bit.

**Comment by benpye** [comment]
You can use the native integer size in C# with IntPtr but it's certainly not a brilliant solution. Using a fixed length integer would be the easiest for C# P/Invoke, either `uint32_t` or `uint64_t` would work I suppose, though the former would avoid a performance penalty on 32 bit platforms. The workaround you've linked to @billyquith is somewhat like what Microsoft does in corefx, however it would be nice to avoid that as it would mean you could have one binding library for .NET everywhere (Windows, Linux, OS X, FreeBSD on x86, x86_64, ARM, etc...).

**Comment by billyquith** [comment]
> either uint32_t or uint64_t would work I suppose, though the former would avoid a performance penalty on 32 bit platforms

It's up to your which one you choose, I just chose 64 bit as it obviously supports 64 bit platforms, which are probably the default now. But I suspect it is unlikely sizes will exceed the range of max uint32_t. However if handles (e.g. opaque pointers) are necessary then 64 bit would be handy, or perhaps another type could be specified for this, but if/when necessary. As you say, `intPtr` could also be used but it a load of hassle for little gain. I think this solution is the best compromise and allows each wrapper the option to chose an appropriate solution.

**Comment by benpye** [comment]
If we have opaque pointers, then that really is when IntPtr is suitable. As
you say, `uint32_t` vs `uint64_t` is a somewhat arbitrary choice.

**Comment by andlabs** [comment]
Leaning toward int, with a requirement that sizeof(int) >= 32 bits, as having 2 billion objects is already unrealistic and poses major usability problems. Design for the trivial case, after all. Any objections?

**Comment by billyquith** [comment]
Do you mean as an addition to the change I suggested, or instead of? My suggestion seems to fix the C# issue.

**Comment by andlabs** [comment]
Which comment has the suggestion you are referring to?

**Comment by billyquith** [comment]
The one 3days ago.

**Comment by andlabs** [comment]
Ah.

There are a few places where size_t is used right now, mainly as "size of array". Every platform I know of has its own convention for dealing with array sizes. For instance, both [C#](https://msdn.microsoft.com/en-us/library/system.array.length(v=vs.110).aspx) and [Go](https://golang.org/ref/spec#Length_and_capacity) use `int` (though the meaning of int differs between the languages) and [Rust uses usize](https://doc.rust-lang.org/std/primitive.slice.html#method.len). So my advice for bindings is to just use that where they see size_t.

But more important is that size_t is unsigned; I need to be able to represent -1, so that won't do. ssize_t is nonstandard.

I'll probably just go with int.

**Comment by andlabs** [comment]
Switched all cases of `intmax_t` and `uintmax_t in the public API to `int`. Hope this helps!
