### ISSUE TITLE
request: add ondestroy handler

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#28]
I propose to create a function either globally:
`uiOnDestroy(void (*ondestroy)(uiControl*, void*))`
or per widget:
`uiControlOnDestroy(uiControl*, void (*ondestroy)(uiControl*, void*))`
The passed handler should be called when any widget / the widget it was registered for is destroyed.

Rationale: I am currently writing a binding for this to lua, which is a language with a garbage collector. When I destroy a toplevel control (like a window), all of the contained controls are destroyed, too. But lua has no way of knowing about this, so when there is still a reference to a control that was used in the window, the next time when the garbage collector comes around, controls may be free()d a second time, which leads to a crash.

**Comment by andlabs** [comment]
I could do this, sure. (Right now my Go bindings keep track of child controls and manually calls `Destroy()` on them as well. Perhaps with this commit I wouldn't need to do that...?)

**Comment by joaoventura** [comment]
This may also be a problem for a python wrapper..

**Comment by gnarz** [comment]
I have started along a similar venue, but that was getting way too complicated. An ondestroy handler seemed like a much simpler approach to me. As all control calls go through one function, this shouldn't be too hard.

**Comment by drbo** [comment]
It should be per-widget.  A global handler is not sufficiently flexible.

**Comment by pcwalton** [comment]
This is wanted for my Rust bindings as well.

What I'm doing now as a workaround is (a) maintaining a list of windows; (b) leaking all controls until `uiUninit()` is called, at which point I iterate over all the windows and destroy them; (c) having every method that calls into the FFI ensure that `uiInit()` has been called and `uiUninit()` has not been called. This essentially creates a weak reference semantics for controls, but it's one that leaks controls until the entire UI system has been shut down.

Another alternative to this approach would be to reference count controls. Effectively, this would make `Control` objects have strong reference semantics instead of weak reference semantics (as in this proposal). In GTK and Cocoa, all controls are already reference counted anyway, so this doesn't add much overhead.

**Comment by andlabs** [comment]
Merged with #325.
