### ISSUE TITLE
uiMenuAppendQuitItem is the only append to menu with a predefined action

### ISSUE THREAD

**Issue by aoloe** [andlabs/libui#32]
i understand that a few menu items have special locations on some systems and have to be handled differently.

but i wonder why uiMenuAppendQuitItem() is the only function that seems to be doing an action on top of adding the entry to the right place.

i would prefer having to add an onClicked() action there, too.

**Comment by andlabs** [comment]
Mainly because OS X has additional facilities to quit the program, most notably the Dock icon, which provides its own Quit option that you cannot configure. How confusing would it be if one Quit item asked you to save files and the other didn't?

The menu API is still very clunky. I'm not sure how to do it better. Accelerator and short<u>c</u>ut differences will also hurt...

**Comment by aoloe** [comment]
good question.
maybe by adding an uiOnQuitting() similar to uiWindowOnClosing()?

and shortcuts and accelerators are the next topics on my list :-)

(btw, as a c++ not-completely-beginner-anymore, i've spent a few hours to get libui to work with c++ and cmake: it was a nice learning experience... a nice multiplatform alternative for simple applications!
next step: wrap libui inside of a few classes that are as close as possible to the way Qt works... do you know if somebody else is already creating a c++ interface?)

**Comment by andlabs** [comment]
uiOnShouldQuit() IS uiOnQuitting() =P You should get to decide whether the quit happens or not. Anything you want to do after quitting you just put after the call to uiMain().

I don't know of any bindings other than my own, sorry.

**Comment by andlabs** [comment]
Replaced with #321.
