### ISSUE TITLE
[POLL] Should I drop OS X 10.7 support?

### ISSUE THREAD

**Issue by andlabs** [andlabs/libui#46]
10.7 has Auto Layout bugs and some missing features, and the people on various OS X dev channels are suggesting I should drop it. Would anyone miss it?

**Comment by joaoventura** [comment]
Another reason (albeit flawed) is that OS X Mavericks is the first non-paid version of OS X, so in theory, everyone could update to that one and even 10.8 could be dropped..

And to agree some more, even the Electron guys (backed by Github) have dropped support for 10.7 (https://github.com/electron/electron/blob/17be978cedce1c0787d6a918c10aa2ef7de564ac/atom/browser/resources/mac/Info.plist#L25-L26)

**Comment by kainjow** [comment]
Yes. Qt 5.6 already dropped it -> http://doc.qt.io/qt-5/supported-platforms-and-configurations.html

**Comment by SevenBits** [comment]
I would support dropping it, or at least using conditionals to test for it. It seems most people have at least Mavericks by now, unless they're on a really old Mac that is stuck on 10.6.

**Comment by sdegutis** [comment]
I'd be surprised if anyone's even still using OS X 10.8 tbh.

**Comment by andlabs** [comment]
@sdegutis There was one person here who reported OS X 10.8 build issues. When I dropped 10.6 support some people also complained about that :)

**Comment by sdegutis** [comment]
@andlabs You can't please everyone. When I write OS X things, the way I see it, I want my software to live as long as possible. The older version I support, the sooner it dies. How many apps that still support OS X 10.4 do you currently have running on your computer? That's why I usually pick the latest or second latest version of OS X to support at minimum. (It sucks that Apple is moving OS versions so quickly, because perceived obsolescence and planned obsolescence are kind of evil, but their plans and actions are not something we can directly change.)

**Comment by andlabs** [comment]
Exactly! 10.6 was simply too hard to build due to various errors in the SDK header files, and 10.7 gave me enough new features to warrant the move. 10.8 doesn't add *much* as far as I can tell; notifications would be handled by another library.

**Comment by sdegutis** [comment]
@andlabs It's not just a matter of building without issue and having useful features. You also should generally make sure the library looks and works right on every platform that you compile for, or at least have someone dedicated to that task. Because it can build fine on 10.10 for 10.9, and you can even test that compiled binary on 10.10, but it's not the same as running that same binary on 10.9, which might actually have visual or functionality issues caused by 10.9 itself. If you're going to support a platform, you have to be 100% sure it works (and looks) as expected on that platform.

**Comment by andlabs** [comment]
Right, that's also my goal as well. I'm just retelling my story =P

**Comment by SevenBits** [comment]
IMO, I don't think this library should support notifications. That seems like too much.

**Comment by andlabs** [comment]
Nobody said no so... switching!

**Comment by billyquith** [comment]
> It sucks that Apple is moving OS versions so quickly, because perceived obsolescence and planned obsolescence are kind of evil

I know this is closed but I thought I'd mention that there were major changes in OSX, including changing primary processor from PowerPC to Intel during OSX 10.5 to 10.9. I think this has driven a lot of these updates. Also much optimisation.

**Comment by sdegutis** [comment]
@billyquith Any optimization in the OS stopped at 10.6. Starting 10.7, they've actually been going the opposite direction, adding more bloat and bugs and making the OS generally run slower on the same hardware.

**Comment by billyquith** [comment]
@sdegutis Well I don't think that is correct. E.g. in [Mavericks](http://www.apple.com/pr/library/2013/10/23OS-X-Mavericks-Available-Today-Free-from-the-Mac-App-Store.html):

> Mavericks also includes new core technologies that boost performance and improve the battery life of your Mac. Timer Coalescing and App Nap™ intelligently save energy and reduce power consumption. Compressed Memory automatically shrinks inactive data to keep your Mac fast and responsive. Mavericks also delivers significant performance enhancements for systems with integrated graphics through optimized OpenCL support and dynamic video memory allocation.

I definitely noticed the difference when this arrived. Anyway, the point is that there have been many changes under the hood so whilst all the upgrades can be frustrating sometimes, especially if the upgrade is buggy, planned obsolescence isn't the reason so we should move with it.

**Comment by andlabs** [comment]
Preemptive lock to avoid flame war
