### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [andlabs/libui#530]

**Comment by franko** [comment]
Sorry about that, I know Meson is not vert good at generating Visual Studio setups and I am sure cmake is better at that.

Actually I am ready to accept a cmake config if someone one to contribute one. The other project's contributors already expressed their disapproval but I am ready to pass over their disagreement.

Meson would remain the main build system we support but cmake could coexist within the project, it will make no harm.

On the other side contributing a working cmake configuration is not trivial especially because of the subprojects lua, libagg and reprod that needs to be configured correctly. I poured a lot of work on these configs using Meson.

**Comment by franko** [comment]
Otherwise, if it is an option for you, you may consider moving to a free software compiler tool-chain on windows.

Microsoft could contribute a better visual studio generator for Meson, they said they love free software! The windows platform is so hostile to software development, outside Visual Studio, that they had to provide a linux VM to all developers to keep them on Windows, I am talking about WSL.

**Comment by graysuit** [comment]
Thank you so much.

While looking the [old PR](https://github.com/andlabs/libui/commit/514b8ecbc6a41096c0d145f397672830d96c6e34#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5R47), I figure out just that command will be needed:  
`python C:\Users\gray\Desktop\meson-0.58.2\meson.py setup build-shared --buildtype=release --backend=vs2017`

and VS2017 project generated under: `/build-shared`

**Comment by graysuit** [comment]
It build fine. I remember it was in my todo to make an wrapper over winapi widgets to make it easy to use.
But its already done by libui. So my intention would be simply use it and contribute. 

And also now I can easily build examples using tcc.
https://github.com/graysuit/libui_examples
