### ISSUE TITLE
libui.js

### ISSUE THREAD

**Issue by mavenave** [andlabs/libui#63]
Hey everyone, show some love here :) https://github.com/mavenave/libui.js very little done so far

**Comment by parro-it** [comment]
Hi @mavenave, I also started to work on node bindings of libui https://github.com/parro-it/libui-node
It could be beautiful to join our efforts! 
I too had done very little so far...

**Comment by Srdgh** [comment]
I've put both your bindings on the wiki for the moment -- if you combine efforts, feel free to update the wiki to reflect that!

**Comment by pcwalton** [comment]
Would be great to see a HTML/CSS port too: the box system of `libui` maps directly to flexbox.

**Comment by parro-it** [comment]
@pcwalton what do you mean exactly by HTML port? 

As you can see [here](https://github.com/parro-it/libui-node/issues/1) me and @mavenave agree to join our efforts on writing node binding.

Next step that we was both planning is to write a react-native sort of framework on top of it...
In that context, we will _probably_ use a subset of CSS to style the UI, using the libui box system as you suggested.

If instead by HTML you mean using libui native widget with javascript in a browser, I don't think this could be technically possible...

By the way, there is also [react-native-desktop](https://github.com/ptmt/react-native-desktop) developed by @ptmt, but it work only for OSX...

**Comment by andlabs** [comment]
I assume you have this progressed now. I'm going to close the issue here; good luck with your bindings!

It's possible to write a server that runs libui code locally and produces results on the browser. In fact, that has already happened indirectly: GTK+ 3 has a backend called "broadway" which renders into a browser. You launch the `broadwayd` program and set `$GDK_BACKEND` appropriately; instructions are in the GTK+ documentation. Only one person can use it at a time and it isn't suitable for web apps, but it's there and it proves this is possible.
