### ISSUE TITLE
Ability to compile as static library (counterpart to #67)

### ISSUE THREAD

**Issue by SevenBits** [andlabs/libui#72]
Apologies if this has already been addressed; please close this if this is the case.

Rather soon I'll be starting work on an application that will not be targeted to technical users, so ease of installation is critical. I'd prefer to only need to distribute a single exe file (for Windows) and binary (for Linux). Is it possible to compile libui as a static library so that this is possible?

**Comment by andlabs** [comment]
Okay, I tried to make this work with Windows, but I ran into two problems, one of which I'm not sure how to fix:

* the comctl32 manifest will need to be specified by the program that links against us since we can't be isolation aware anymore (not a problem, just documentation)...
* ...but it seems the link process **overwrites libui's resources with the application's**. This means tabs, the font dialog, and the color dialog won't work and will crash the program.

I'm not sure how to fix that latter bullet. Any ideas? @pcwalton?

**Comment by pcwalton** [comment]
Apparently we need to ship both a `.lib` and a `.res`. The user then drags both the `.lib` and the `.res` into their project, and apparently this works. See http://stackoverflow.com/a/1631078.

**Comment by andlabs** [comment]
Hm; I could probably hack that in easily, yes...

**Comment by andlabs** [comment]
All right, I think I fixed it.

**Comment by andlabs** [comment]
Okay, new problem. Lots of the following when linking executables on linux 32-bit:

```
`__x86.get_pc_thunk.bx' referenced in section `.text' of out/libui.a(libui.o): defined in discarded section `.text.__x86.get_pc_thunk.bx[__x86.get_pc_thunk.bx]' of out/libui.a(libui.o)
`__x86.get_pc_thunk.ax' referenced in section `.text' of out/libui.a(libui.o): defined in discarded section `.text.__x86.get_pc_thunk.ax[__x86.get_pc_thunk.ax]' of out/libui.a(libui.o)
```

Not sure how to fix this one; Google isn't helping/only gives me answers for shared libraries.

**Comment by pcwalton** [comment]
My instinct tells me that this may be due to PIC/non-PIC compile flags being set incorrectly. We shouldn't be using `-fPIC` for static libraries.

**Comment by andlabs** [comment]
Yep, that was it; thanks.

**Comment by andlabs** [comment]
The limitations of MinGW that prevented me from allowing it for a shared library don't apply to a static library, and since mixing and matching isn't really possible (I tried), I'm going to have to provide separate static libraries for MinGW and MSVC (as an Alpha 3.1). I'll take this to #62.

I want to try the other Unix systems before closing this PR.

**Comment by andlabs** [comment]
Done. I'll try other Unix systems over time.
