### ISSUE TITLE
question about window and platform features like focus, always-on-top, icon, growl like notificaton

### ISSUE THREAD

**Issue by seven1240** [andlabs/libui#78]
Hi,

I tested libui on Mac it's awesome.

Would like to ask is it already has or do you have a plan for -

- mainWin focus. Currently when start the main window does't show on top
- always on top. maybe for a video/message window to stay on top
- icon show a nice icon on the dock bar
- growl like message notification

so it's really a native App.

Also, hint or docs to help make a Mac bundle would be cool.

Thanks.

**Comment by andlabs** [comment]
Window focus is an OS X-specific issue; I don't force it on because it would interfere with .app bundles. (If you run from the command line, your window isn't focused by default, but if you run from a .app bundle, it will be.) See #20 for details (and especially the linked Stack Overflow question for technical information).

Not sure what I'll do about always on top.

Dock icons can also be set from the .app bundle. I'm not sure how you would set a Dock icon outside of a .app bundle (but I know it can be done).

Notifications I have already decided would be relegated to a separate library.

**Comment by seven1240** [comment]
Thanks for your response. I'm able to create a bundle now: http://stackoverflow.com/questions/1596945/building-osx-app-bundle

And it lead me the another question: should libui to i18n or other lib ?

**Comment by andlabs** [comment]
I don't understand the question; what do you mean?

**Comment by seven1240** [comment]
I'm from China I mean https://en.wikipedia.org/wiki/Internationalization_and_localization

maybe this belongs to other lib like gettext . Not sure.

Thanks for your quick response again. I think I can clost this one.

**Comment by andlabs** [comment]
Localization would be done through something like gettext or the lproj files in Xcode, yeah. libui uses UTF-8 for all strings, so it doesn't need extra work to handle localization to LTR languages. Not sure if it will work right on RTL languages, or how to test it, but I did take as many precautions as I can right now to ensure it does.
